In [ ]:
#Tuple Operations
import statistics
import pandas as pd

# Read the Excel file
df = pd.read_excel('/content/drive/MyDrive/HPSV.EDS.xls')

print(df)

tuple_data = tuple(map(tuple, df.values))

print(tuple_data)


operation1 = max(Price Paid)
operation2 = min(,Price Paid)
Operation3= sum(,Price Paid)
operation4 = statistics.median(,Price Paid)

print("max: ",operation1 )

SyntaxError: ignored